Two approaches to Lighthouse integration
1. Use Lighthouse CI Action
2. Use original Lighthouse CI from npm 
Both are scheduled work on Netlify deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-# From https://github.com/marketplace/actions/lighthouse-audit
+# From https://github.com/marketplace/actions/wait-for-netlify
 name: Lighthouse CI for Netlify deployment
 on:
   push:
@@ -6,7 +6,8 @@ on:
   pull_request:
     branches: [ master ]
 jobs:
-  lighthouse-audit:
+  lighthouse-audit-1:
+    name: Lighthouse Audit 1
     runs-on: ubuntu-latest
     steps:
       # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
@@ -15,7 +16,7 @@ jobs:
       - name: Wait for Netlify deployment
         uses: jakepartusch/wait-for-netlify-action@v1
         with:
-          site_name: zinzan
+          site_name: "zinzan"
       # Based on netlify url, run Lighthouse audit
       - name: Run Lighthouse audit
         uses: treosh/lighthouse-ci-action@v3
@@ -23,3 +24,32 @@ jobs:
           urls: https://zinzan.netlify.app
           uploadArtifacts: true # save results as an action artifacts
           temporaryPublicStorage: true # upload lighthouse report to the temporary storage
+  lighthouse-audit-2:
+    name: Lighthouse audit 2
+    runs-on: ubuntu-latest
+    steps:
+      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
+      - uses: actions/checkout@v2
+      # Install node.js and npm
+      - name: Use Node.js 12.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+      - name: Install
+        run: |
+          npm ci
+      - name: Build
+        run: |
+          npm run build
+      # Wait for Netlify deployment at zinzan.netlify.app
+      - name: Wait for Netlify deployment
+        uses: jakepartusch/wait-for-netlify-action@v1
+        id: netlify
+        with:
+          site_name: "zinzan"
+      - name: Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.5.x
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.netlify.outputs.url }} || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_SERVER_TOKEN }}
